added sum of numbers
js-tasks-ru/jsbasic-20201113_mariayevlakova pull request #1
Opened 2020-11-16 10:35 UTC by mariayevlakova

2020-11-16 10:52 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Первая задача
+ 1+1=2
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-11-21 14:27 UTC, koalex requested changes
@mariayevlakova Исправь замечание.

2020-11-21 14:27 UTC, koalex commented on 0-module/1-task/index.js
> +sum(2, 5);
удали строки 11 и 12

2020-11-21 15:27 UTC, koalex approved these changes

2020-11-21 15:27 UTC, merged